### ISSUE TITLE
Would like some help on how to get this running

### ISSUE THREAD

**Issue by SerpentDrago** [membersheep/telegram-mumble-bot#1]
I created an account on https://www.heroku.com/ 

Forked this and set the api variable and Deployed it .  There is still nothing from my bot in telegram . is there special commands ? how do i tell it what my mumble server is ? 

Help would be great . I've tried getting hold of every person that has a Mumble/telegram notification bot and nothing. I've tried everything i can !

**Comment by SerpentDrago** [comment]
OMG , I just got it working !  No Need for help now , saw the var i needed and set them ! it works it works ! THANKS MAN

**Comment by SerpentDrago** [comment]
Is there anyway to interact with the Telegram bot  ?

**Comment by membersheep** [comment]
Hi SerpentDrago, 
I'm glad you finally make it work by yourself! I should definitely write a more detailed guide. Right now the bot is passive and it just notifies events/messages happening on mumble server. What kind of interactions where you imagining?

**Comment by membersheep** [comment]
I'm closing this issue since you solved it. Please open a new issue for other requests and suggestions.

**Comment by mayailkour** [comment]
Is it possible to setup the bot on an Ubuntu VPS (e.g. from [Hetzner](https://hetzner.cloud/) or [DigitalOcean](https://www.digitalocean.com/products/droplets/))?

**Comment by membersheep** [comment]
Hello @mayailkour ,
I'm sure it is possible since both nodejs and mumble run on ubuntu.
